/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.icednut.adapter.exercise;

import io.icednut.adapter.exercise.search.service.SearchService;
import io.icednut.adapter.exercise.search.service.SearchServiceTolrAdapter;
import io.icednut.adapter.exercise.search.service.SearchServiceTolrAdapter2;

public class App {

    public static void main(String[] args) {
        SearchService service = new SearchServiceTolrAdapter();
        service.search("gof");

        SearchService service2 = new SearchServiceTolrAdapter2();
        service2.search("gof");
    }
}
